"""
HunterAI Cross-Sensor Tool Agreement Engine
===========================================
Correlates findings across independent telemetry channels:
- Burp Proxy / Gateway HTTP history
- Playwright Browser DOM events
- Raw HTTP Differential Analysis
- Proof of Execution (PoE) token verification
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class SensorSignals:
    burp_observed: bool = False
    browser_dom_executed: bool = False
    http_diff_confirmed: bool = False
    poe_token_verified: bool = False
    waf_blocked: bool = False
    is_reflection_only: bool = False


class ToolAgreementEngine:
    """Evaluates cross-sensor agreement and refutes unverified claims"""

    @classmethod
    def evaluate(cls, signals: SensorSignals) -> Dict[str, Any]:
        # Consensus counting
        agreeing_sensors = 0
        if signals.burp_observed:
            agreeing_sensors += 1
        if signals.browser_dom_executed or signals.poe_token_verified:
            agreeing_sensors += 2  # High-value execution signal
        if signals.http_diff_confirmed:
            agreeing_sensors += 1

        agreement_ratio = min(1.0, agreeing_sensors / 3.0)

        # Fatal Contradiction Check: Reflection without execution
        if signals.is_reflection_only and not signals.browser_dom_executed and not signals.poe_token_verified:
            return {
                "verdict": "REJECTED",
                "reason": "Reflection without execution detected (Input echoed into DOM without script execution context).",
                "agreement_score": 0.1,
                "is_valid": False
            }

        if signals.waf_blocked:
            return {
                "verdict": "REJECTED",
                "reason": "Response was generated by Cloudflare / WAF block rather than backend target execution.",
                "agreement_score": 0.1,
                "is_valid": False
            }

        is_valid = agreement_ratio >= 0.6
        return {
            "verdict": "CONFIRMED" if is_valid else "INSUFFICIENT_EVIDENCE",
            "reason": f"Tool agreement established with score {agreement_ratio:.2f}.",
            "agreement_score": agreement_ratio,
            "is_valid": is_valid
        }
