"""
Burp Issue Exporter
===================
Translates confirmed Evidence Court findings into standard Burp Suite IScanIssue format.
Allows Burp Suite to import HunterAI confirmed vulnerabilities into the Target Issues tab.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List
from urllib.parse import urlparse

logger = logging.getLogger("hunter_ai.issue_exporter")


class BurpIssueExporter:
    """Formats findings as standard Burp Scanner Issues"""

    SEVERITY_MAP = {
        "Critical": "High",
        "High": "High",
        "Medium": "Medium",
        "Low": "Low",
        "Info": "Information",
    }

    CONFIDENCE_MAP = {
        "CONFIRMED": "Certain",
        "HIGH": "Firm",
        "MEDIUM": "Tentative",
        "UNVERIFIED": "Tentative",
    }

    @classmethod
    def format_finding_for_burp(cls, finding: Dict[str, Any]) -> Dict[str, Any]:
        """
        Converts a finding into Burp Suite compatible JSON representation
        """
        url = finding.get("endpoint") or finding.get("target") or "http://target.local/"
        parsed = urlparse(url)
        host = parsed.hostname or "target.local"
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        protocol = parsed.scheme or "http"

        title = finding.get("title") or f"{finding.get('type', 'Vulnerability').upper()} Detected"
        raw_sev = finding.get("severity", "Medium")
        burp_sev = cls.SEVERITY_MAP.get(raw_sev, "Medium")

        verdict = finding.get("lifecycle_verdict", "CONFIRMED")
        burp_conf = cls.CONFIDENCE_MAP.get(verdict, "Certain")

        detail = finding.get("evidence") or finding.get("remediation") or "Vulnerability verified by HunterAI Evidence Court."
        remediation = finding.get("remediation") or "Remediate according to OWASP guidelines."

        return {
            "issue_name": f"[HunterAI] {title}",
            "issue_type": 0x08000000,  # Extension issue code
            "severity": burp_sev,
            "confidence": burp_conf,
            "host": host,
            "port": port,
            "protocol": protocol,
            "url": url,
            "path": parsed.path or "/",
            "issue_background": "Discovered and mathematically confirmed by HunterAI Evidence Court.",
            "issue_detail": f"<b>HunterAI Evidence Court Verdict:</b> {verdict}<br/><br/><b>Details:</b><br/>{detail}<br/><br/><b>Proof-of-Execution:</b> {finding.get('payload_used', 'N/A')}",
            "remediation": remediation,
            "remediation_background": remediation,
            "remediation_detail": f"Apply context-aware controls: {remediation}",
            "http_messages": [
                {
                    "request": finding.get("raw_request", ""),
                    "response": finding.get("raw_response", ""),
                    "comment": f"Proof generated by HunterAI ({finding.get('tool', 'AutonomousBrain')})"
                }
            ] if finding.get("raw_request") else []
        }

    @classmethod
    def export_all(cls, findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        return [cls.format_finding_for_burp(f) for f in findings]
