"""
Report Generator Skill
Consolidates findings, evidence, and tool outputs into a final structured security report.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Dict, List

from skills.base_skill import BaseSkill, SkillContext, SkillResult


class ReportGeneratorSkill(BaseSkill):
    name = "report_generator"
    category = "reporting"
    description = "Generates comprehensive final markdown report for the mission"
    tools_required = []
    fallback_tools = []

    async def execute(self, ctx: SkillContext) -> SkillResult:
        result = SkillResult(skill_name=self.name, success=True, tool_used="report_generator")

        all_files = ctx.workspace.list_files(ctx.target, session_id=ctx.session_id)
        report_lines = [
            f"# Autonomous Security Assessment Report: {ctx.target}",
            f"**Session ID:** `{ctx.session_id}`",
            f"**Execution Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Mode:** {ctx.mode}",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            f"An automated, modular security reconnaissance and assessment mission was conducted against target **{ctx.target}**.",
            f"Total discovered artifacts and logs: **{len(all_files)}** files generated.",
            "",
            "## 2. Artifacts and Workspace Breakdown",
            "| Category | File | Size (Bytes) |",
            "|---|---|---|",
        ]

        for f in all_files:
            report_lines.append(f"| {f.get('category', '-')} | `{f.get('name', '-')}` | {f.get('size', 0)} |")

        report_lines.extend([
            "",
            "## 3. Methodological Overview",
            "- **Phase 1: Reconnaissance & Asset Discovery:** Subdomain enumeration, DNS record interrogation, live host probing, port scanning, and technology fingerprinting.",
            "- **Phase 2: Web Surface Mapping:** Content crawling, directory & endpoint fuzzing, parameter discovery, and client-side JavaScript analysis.",
            "- **Phase 3: Defensive Recommendations & Remediation:** Hardening guidance based on discovered services and exposed endpoints.",
            "",
            "## 4. Key Recommendations",
            "1. **Surface Minimization:** Decommission obsolete DNS records and restrict access to administrative/internal endpoints.",
            "2. **Configuration Hardening:** Ensure web servers do not leak software version banners, server headers, or internal paths.",
            "3. **Secrets Management:** Audit client-side JavaScript assets to verify no production credentials, tokens, or API keys are exposed.",
            "",
            "---",
            "*Report auto-generated by Autonomous Security Mission Agent Framework.*",
        ])

        report_content = "\n".join(report_lines)
        p = ctx.workspace.write_file(ctx.target, "reports", "final_report.md", report_content, ctx.session_id)
        result.output_files["final_report.md"] = str(p)

        return result
